########################################################
# Docker Image version, common for sdk and sdk tunnel
########################################################
variables:
  ANDROID_R17C_IMAGE_VERSION: 20210407_update_cmake_3_20
  ANDROID_R20_IMAGE_VERSION: 20210914_update_java11
  ARCHLINUX_IMAGE_VERSION: latestupdated
  ARCHLINUX_TEST_LIBLIN_IMAGE_VERSION : 20210217_init
  CENTOS_7_IMAGE_VERSION: 20210421_python3_fix_pip
  CENTOS_7_TEST_LIBLIN_IMAGE_VERSION: 20210217_python3
  CENTOS_8_IMAGE_VERSION: 20211008_python3.9_cython_wheel_pdoc3
  CENTOS_8_TEST_LIBLIN_IMAGE_VERSION: 20210217_python3
  DEBIAN_8_IMAGE_VERSION: 20210217_python3
  DEBIAN_9_IMAGE_VERSION: 20210421_python3_fix_pip
  DEBIAN_9_TEST_LIBLIN_IMAGE_VERSION: 20210217_python3
  DEBIAN_9_METABC_YOCTO_IMAGE_VERSION: 20210304_python3
  DEBIAN_10_IMAGE_VERSION: 20210421_python3_fix_pip
  DEBIAN_10_TEST_LIBLIN_IMAGE_VERSION: 20210217_python3
  UBUNTU_ROLLING_IMAGE_VERSION: 20210217_python3
  UBUNTU_ROLLING_TEST_LIBLIN_IMAGE_VERSION: 20210217_python3
