# /!\ Important point to note :
# If we are using two podspec upload jobs on a same machine on the same time there might be a race condition during podspec repo add of one job and the delete of the other.
# This is because the location of Cocoapods repository is stored in ~/.cocoapods and is not configurable...
# So uploads are parallelized only by using multiple machines (having one specific runner for upload installed on each, and a common tag)

.ios-xcode-podspec-upload:
  stage: deploy
  variables:
    PODNAME: "linphone-sdk"
    PODSPEC_END_PATH: ""
    GIT_FETCH_EXTRA_FLAGS: --tags --force --recurse-submodules=yes
    GIT_SUBMODULE_UPDATE_FLAGS: --jobs 8 --force --recursive
  rules:
    - if: $DEPLOY_RUN_IOS
    - if: $NIGHTLY_MASTER && $SKIP_DEPLOY == null
    - if: $NIGHTLY_RELEASE
  needs:
    - ios-xcode

  script:

    #Only get major and minor version (ex: 4.5) for documentation directory

    #git -C executes the git command in specified directory
    #grep options:
    #-o means print only matched pattern instead of whole line
    #-E means extended regexp, see https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions
    - DESCRIBE=$(git -C liblinphone describe)
    - echo $DESCRIBE

    - LIBLINPHONE_VERSION=$(echo $DESCRIBE | grep -o -E '^[0-9]+\.[0-9]+')

    - !reference [.choose_upload_dir, script]

    # Doc upload, we only do it for ios-xcode job, as ios-xcode-no-video one doesn't have doc enabled, we then differenciate between the two with the podname
    # Create the directory if it does not exist
    - if [ $PODNAME = "linphone-sdk" ]; then ssh $DEPLOY_SERVER mkdir -p $UPLOAD_ROOT_DIRECTORY/docs/liblinphone/$LIBLINPHONE_VERSION/swift; fi

    #using rsync with following options(verbose, keeping symbolic links, and copy recursively)
    - if [ $PODNAME = "linphone-sdk" ]; then rsync -rlv build/ios/docs/* $DEPLOY_SERVER:$UPLOAD_ROOT_DIRECTORY/docs/liblinphone/$LIBLINPHONE_VERSION/swift; fi

    - echo $PODSPEC_END_PATH
    - echo $PODNAME

    - ls -lah build/ios

    - if timeout --signal=SIGINT 1 xcrun simctl list; then echo "show all devices"; else killall -9 com.apple.CoreSimulator.CoreSimulatorService; echo "restart core service"; fi

    - echo $UPLOAD_ROOT_DIRECTORY
    - scp build/ios/linphone-sdk-*.zip $DEPLOY_SERVER:$UPLOAD_ROOT_DIRECTORY/ios/$PODSPEC_END_PATH
    - pod repo remove $PODNAME || true
    - pod repo add $PODNAME git@gitlab.linphone.org:BC/public/podspec.git
    - pod repo push $PODNAME build/ios/$PODNAME.podspec --skip-import-validation --verbose
    - pod repo remove $PODNAME

.ios-xcode-novideo-upload:
  needs:
    - ios-xcode-novideo
  variables:
    PODSPEC_END_PATH: "novideo/"
    PODNAME: "linphone-sdk-novideo"

  extends: .ios-xcode-podspec-upload

ios-xcode-upload-xcode12:
  extends: .ios-xcode-podspec-upload
  tags: [ "macosx-min-xcode12.2-upload" ]

ios-xcode-novideo-upload-xcode12:
  extends: .ios-xcode-novideo-upload
  tags: [ "macosx-min-xcode12.2-upload" ]
