########################################################
# Docker Image version, common for sdk and sdk tunnel
########################################################
variables:
  ANDROID_R25B_IMAGE_VERSION: 20230706_add_deps_for_av1
  ARCHLINUX_IMAGE_VERSION: 20230706_add_deps_for_av1
  ARCHLINUX_TEST_LIBLIN_IMAGE_VERSION: 20230706_add_deps_for_av1
  CENTOS_8_IMAGE_VERSION: 20230706_add_deps_for_av1
  CENTOS_8_TEST_LIBLIN_IMAGE_VERSION: 20230706_add_deps_for_av1
  DEBIAN_10_IMAGE_VERSION: 20230706_add_deps_for_av1
  DEBIAN_10_TEST_LIBLIN_IMAGE_VERSION: 20230706_add_deps_for_av1
  DEBIAN_11_IMAGE_VERSION: 20230706_add_deps_for_av1
  DEBIAN_11_TEST_LIBLIN_IMAGE_VERSION: 20230706_add_deps_for_av1
  DEBIAN_12_IMAGE_VERSION: 20230706_add_deps_for_av1
  DEBIAN_12_TEST_LIBLIN_IMAGE_VERSION: 20230706_add_deps_for_av1
  ROCKY_8_IMAGE_VERSION: 20230905_add_rocky8_sdk
  ROCKY_8_TEST_LIBLIN_IMAGE_VERSION: 20230905_add_rocky8_sdk
  RASPIOS_IMAGE_VERSION: 20230706_add_deps_for_av1
  UBUNTU_ROLLING_IMAGE_VERSION: 20230802_fix_wrong_user_id
  UBUNTU_ROLLING_TEST_LIBLIN_IMAGE_VERSION: 20230802_fix_wrong_user_id
  UBUNTU_1804_IMAGE_VERSION: 20230706_add_deps_for_av1
  UBUNTU_1804_TEST_LIBLIN_IMAGE_VERSION: 20230706_add_deps_for_av1
