.linux-prepare:

  cache:
    key: $CI_JOB_NAME
    paths:
      - ccache/

  before_script:
    ##
    ## If a TUNNEL_USER_KEY is defined then start ssh-agent and add the key
    ##
    - if ! [ -z ${TUNNEL_USER_KEY+x} ]; then eval $(ssh-agent -s); fi
    - if ! [ -z ${TUNNEL_USER_KEY+x} ]; then echo "$TUNNEL_USER_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi
    - if ! [ -z ${TUNNEL_USER_KEY+x} ]; then mkdir -p ~/.ssh && chmod 700 ~/.ssh; fi

    ##
    ## Configure git if necessary
    ##
    - if ! [ -z ${TUNNEL_USER_NAME+x} ]; then git config --global user.name "$TUNNEL_USER_NAME"; fi
    - if ! [ -z ${TUNNEL_USER_MAIL+x} ]; then git config --global user.email "$TUNNEL_USER_MAIL"; fi

    ##
    ## Then configure ccache
    ##
    - mkdir -p ccache
    - echo "max_size = $CCACHE_SIZE" > ccache/ccache.conf
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
    - ccache -s

  after_script:
    - if ! [ -z ${TUNNEL_USER_KEY+x} ]; then rm ~/.ssh/id_rsa || true; fi
    - export CCACHE_DIR=${PWD}/ccache
    - ccache -s
