#!/usr/bin/env python3
"""
retry_failed_tests.py

Parses a JUnit XML report generated by liblinphone-tester, identifies any failed tests,
and re-runs each failed test sequentially using liblinphone-tester.
If a retried test succeeds, the JUnit XML report is updated to reflect the success.
Exits with 0 if all tests pass (or if there were no failures to begin with), or 1 if any retried test still fails.
"""

import argparse
import os
import re
import shlex
import subprocess
import sys
import time
import xml.etree.ElementTree as ET


def check_symbolizer():
    """
    Verifies that llvm-symbolizer is present and executable, and prints its version for diagnostic purposes.
    """
    symbolizer = os.environ.get("ASAN_SYMBOLIZER_PATH") or "/usr/bin/llvm-symbolizer"
    if os.path.isfile(symbolizer) and os.access(symbolizer, os.X_OK):
        try:
            res = subprocess.run([symbolizer, "--version"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
            first_line = res.stdout.strip().splitlines()[0] if res.stdout.strip() else "available"
            print(f"  llvm-symbolizer ({symbolizer}): {first_line}")
        except Exception as e:
            print(f"  llvm-symbolizer ({symbolizer}): error running --version: {e}")
    else:
        print(f"  WARNING: llvm-symbolizer not found or not executable at '{symbolizer}'")


def find_failed_tests(tree):
    """
    Finds all failed testcases in the JUnit XML report.
    Returns a list of dicts:
    [
        {
            'suite_element': <testsuite element>,
            'suite_name': str,
            'test_element': <testcase element>,
            'test_name': str,
            'failure_element': <failure element>
        }, ...
    ]
    """
    root = tree.getroot()
    failed_tests = []

    # Handle both <testsuites><testsuite>... and direct <testsuite> root
    testsuites = root.findall(".//testsuite")
    if not testsuites and root.tag == "testsuite":
        testsuites = [root]

    for suite in testsuites:
        suite_name = suite.get("name", "")
        for tc in suite.findall("testcase"):
            # Check for failure or error tag
            failure = tc.find("failure")
            error = tc.find("error")
            fail_elem = failure if failure is not None else error

            if fail_elem is not None:
                test_name = tc.get("name", "")
                failed_tests.append({
                    "suite_element": suite,
                    "suite_name": suite_name,
                    "test_element": tc,
                    "test_name": test_name,
                    "failure_element": fail_elem,
                })

    return failed_tests


def sanitize_name(name):
    """
    Sanitizes a suite or test name to be safely used in filenames.
    Replaces spaces and path/special/shell characters with underscores.
    """
    sanitized = re.sub(r'[\s/\\:*?"<>|()]+', '_', name.strip())
    sanitized = re.sub(r'_+', '_', sanitized)
    return sanitized.strip('_')


def generate_log_filename(suite_name, test_name, log_dir=None):
    """
    Generates a log filename based on suite name and test name:
    <clean_suite>_<clean_test>.log
    """
    clean_suite = sanitize_name(suite_name)
    clean_test = sanitize_name(test_name)
    filename = f"{clean_suite}_{clean_test}.log"
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)
        return os.path.join(log_dir, filename)
    return filename


def strip_log_file_arg(args_list):
    """
    Removes any existing --log-file or --log-file= arguments from the list.
    """
    filtered = []
    skip_next = False
    for arg in args_list:
        if skip_next:
            skip_next = False
            continue
        if arg == "--log-file":
            skip_next = True
            continue
        if arg.startswith("--log-file="):
            continue
        filtered.append(arg)
    return filtered


def run_single_test(tester_bin, suite_name, test_name, extra_args_list=None, log_dir=None, env=None):
    """
    Executes a single test sequentially using tester_bin:
    <tester_bin> --verbose --suite "<suite_name>" --test "<test_name>" --log-file "<log_file>" <extra_args>
    Returns (returncode, stdout + stderr, duration_seconds)
    """
    log_file = generate_log_filename(suite_name, test_name, log_dir=log_dir)
    cmd = [tester_bin, "--verbose", "--suite", suite_name, "--test", test_name, "--log-file", log_file]
    if extra_args_list:
        cmd.extend(extra_args_list)

    print(f"\n==================================================")
    print(f"Running retry for: suite='{suite_name}' test='{test_name}'")
    print(f"Log file: {log_file}")
    print(f"Command: {' '.join(shlex.quote(c) for c in cmd)}")
    print(f"==================================================")

    start_time = time.time()
    try:
        proc = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True,
            env=env,
        )
        duration = time.time() - start_time
        print(proc.stdout)
        print(f"-> Result: {'PASSED' if proc.returncode == 0 else 'FAILED'} (code: {proc.returncode}, took {duration:.2f}s)")
        return proc.returncode, proc.stdout, duration
    except Exception as e:
        duration = time.time() - start_time
        print(f"-> Error launching test: {e}")
        return -1, str(e), duration


def update_xml_for_passed_test(test_info, new_duration):
    """
    Removes the failure/error tag from test_element and updates counters.
    """
    suite_elem = test_info["suite_element"]
    tc_elem = test_info["test_element"]
    fail_elem = test_info["failure_element"]

    # Remove failure tag
    tc_elem.remove(fail_elem)

    # Update execution time
    tc_elem.set("time", f"{new_duration:.6f}")
    tc_elem.set("retried", "true")

    # Update suite failure count
    failures_str = suite_elem.get("failures", "0")
    try:
        failures = int(failures_str)
        if failures > 0:
            suite_elem.set("failures", str(failures - 1))
    except ValueError:
        pass


def update_total_suite_counters(tree):
    """
    Recalculates testsuites root attributes if present (tests, failures, errors).
    """
    root = tree.getroot()
    if root.tag == "testsuites":
        total_failures = 0
        total_errors = 0
        for suite in root.findall(".//testsuite"):
            try:
                total_failures += int(suite.get("failures", 0))
            except ValueError:
                pass
            try:
                total_errors += int(suite.get("errors", 0))
            except ValueError:
                pass
        root.set("failures", str(total_failures))
        root.set("errors", str(total_errors))


def save_xml_report(tree, output_file):
    """
    Writes the XML tree back to file with proper XML declaration.
    """
    try:
        ET.indent(tree, space="  ")
    except AttributeError:
        pass  # Python < 3.9 fallback
    tree.write(output_file, encoding="UTF-8", xml_declaration=True)
    print(f"Updated JUnit XML written to: {output_file}")


def main():
    parser = argparse.ArgumentParser(description="Retry failed liblinphone tests sequentially from JUnit XML.")
    parser.add_argument("--xml", required=True, help="Path to JUnit XML report to parse and update.")
    parser.add_argument("--xml-out", help="Path to save updated JUnit XML (defaults to --xml).")
    parser.add_argument("--tester-bin", required=True, help="Path to tester binary (e.g. liblinphone-tester).")
    parser.add_argument("--max-retries", type=int, default=5, help="Maximum number of failed tests allowed to retry (default: 5). If exceeded, fails immediately without retrying.")
    parser.add_argument("--log-dir", help="Directory where per-test log files should be written.")
    parser.add_argument("--extra-args", default="", help="Extra arguments string to pass to tester binary.")
    parser.add_argument("tester_options", nargs=argparse.REMAINDER, help="Any additional tester options.")

    args = parser.parse_args()

    xml_path = args.xml
    output_xml_path = args.xml_out or xml_path
    tester_bin = args.tester_bin
    max_retries = args.max_retries
    log_dir = args.log_dir

    raw_extra_args = []
    if args.extra_args:
        raw_extra_args.extend(shlex.split(args.extra_args))
    if args.tester_options:
        raw_extra_args.extend(args.tester_options)
    extra_args_list = strip_log_file_arg(raw_extra_args)

    if not os.path.exists(xml_path):
        print(f"Error: JUnit XML report '{xml_path}' not found!")
        return 1

    if not os.path.exists(tester_bin) and not os.access(tester_bin, os.X_OK):
        print(f"Error: Tester binary '{tester_bin}' not found or not executable!")
        return 1

    print("=== Environment Diagnostics ===")
    lsan = os.environ.get("LSAN_OPTIONS")
    asan = os.environ.get("ASAN_OPTIONS")
    print(f"  LSAN_OPTIONS: {lsan}")
    print(f"  ASAN_OPTIONS: {asan}")
    print(f"  ASAN_SYMBOLIZER_PATH: {os.environ.get('ASAN_SYMBOLIZER_PATH')}")
    check_symbolizer()
    if lsan:
        for part in lsan.split(":"):
            if part.startswith("suppressions="):
                supp_path = part.split("=", 1)[1]
                exists = os.path.exists(supp_path)
                size = os.path.getsize(supp_path) if exists else 0
                print(f"  Suppression file '{supp_path}': exists={exists}, size={size} bytes")
    print("================================")

    try:
        tree = ET.parse(xml_path)
    except ET.ParseError as e:
        print(f"Error parsing XML '{xml_path}': {e}")
        return 1

    failed_tests = find_failed_tests(tree)
    if not failed_tests:
        print("No failed tests found in the JUnit XML report. Everything already passed!")
        return 0

    num_failed = len(failed_tests)
    if num_failed > max_retries:
        print(
            f"Error: {num_failed} tests failed in the initial run, which exceeds the maximum allowed limit of {max_retries}.\n"
            f"This indicates a general issue or regression rather than transient network/SIP flakiness.\n"
            f"Aborting 2nd-chance retry immediately."
        )
        return 1

    print(f"Found {num_failed} failed test(s) in '{xml_path}'. Starting retry sequence...")

    all_passed = True
    any_updated = False

    for test_info in failed_tests:
        suite_name = test_info["suite_name"]
        test_name = test_info["test_name"]

        retcode, output, duration = run_single_test(
            tester_bin=tester_bin,
            suite_name=suite_name,
            test_name=test_name,
            extra_args_list=extra_args_list,
            log_dir=log_dir,
        )

        if retcode == 0:
            print(f"Test '{suite_name} / {test_name}' PASSED on 2nd chance! Updating XML report.")
            update_xml_for_passed_test(test_info, duration)
            any_updated = True
        else:
            print(f"Test '{suite_name} / {test_name}' FAILED on 2nd chance.")
            all_passed = False

    if any_updated:
        update_total_suite_counters(tree)
        save_xml_report(tree, output_xml_path)

    if all_passed:
        print("\nAll retried tests passed successfully on 2nd chance! Job succeeded.")
        return 0
    else:
        print("\nSome tests still failed after 2nd chance retry. Job failed.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
