java-linux-package:
  stage: package
  tags: [ "docker" ]
  image: !reference [.debian12_java_image_version, image]
  extends: .linux-prepare
  variables:
    GIT_STRATEGY: fetch
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_RUN_MAVEN_JAVA_LINUX != null
  script:
   - mkdir -p build-java-wrapper
   - cd build-java-wrapper
   - cmake -GNinja --preset=java-sdk-linux -DENABLE_CCACHE=ON ..
   - cmake --build .
  artifacts:
    paths:
      # Needed of uploads
      - build-java-wrapper/build.gradle
      - build-java-wrapper/upload.gradle
      - build-java-wrapper/gradle.properties
      - build-java-wrapper/linphone-sdk/bin/libs/*
    when: always
    expire_in: 2 days
