java-linux-upload:
  stage: package
  tags: [ "docker" ]
  image: !reference [.android_r27_image_version, image]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_RUN_MAVEN_JAVA_LINUX != null
  variables:
    GIT_STRATEGY: fetch
    MAVEN_REPO_URL: $ANDROID_MAVEN_URL
  needs:
    - job: java-linux-package
  before_script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_USER_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$DEPLOY_SERVER_HOST_KEY" >> ~/.ssh/known_hosts
  script:
    - cd build-java-wrapper
    - mkdir -p maven_repository/org/linphone/
    - echo $MAVEN_REPO_PATH
    - rsync -avzP -e ssh --exclude "*.jar" $MAVEN_REPO_URL/org/linphone/linphone-sdk maven_repository/org/linphone/
    - echo $GRADLE_OPTIONS
    - ../cmake/Java/gradlew -b upload.gradle publish $GRADLE_OPTIONS
    - rsync -avzP -e ssh ./maven_repository/org/linphone/linphone-sdk $MAVEN_REPO_URL/org/linphone/
  after_script:
    - rm -rf ~/.ssh || true
