#Build template to use in other job scripts without having to copy same code
#format = .className: &referenceName
#Use = "<< *referenceName" to use the template ("-*" in script)


.factorize_debian12: &docker_image_platform_and_runner_tag
  tags: [ "docker-test" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian12:$DEBIAN_12_IMAGE_VERSION
  variables:
    PLATFORM: linux-debian12

#################################################
# Makefile
#################################################


debian12-makefile-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian12:$DEBIAN_12_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .linux-desktop


debian12-makefile-clang:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian12:$DEBIAN_12_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .linux-desktop


#################################################
# Ninja
#################################################


debian12-ninja-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian12:$DEBIAN_12_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
    CMAKE_OPTIONS: -DENABLE_LDAP=NO
  extends: .linux-desktop


debian12-ninja-gcc-novideo:
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_LDAP=NO
  extends: debian12-ninja-gcc

debian12-ninja-gcc-pqc:
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_PQCRYPTO=YES -DENABLE_LDAP=NO
  extends: debian12-ninja-gcc

debian12-ninja-gcc-smallsdk:
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_ADVANCED_IM=NO -DENABLE_DB_STORAGE=NO -DENABLE_FLEXIAPI=NO -DENABLE_LDAP=NO
  extends: debian12-ninja-gcc


debian12-ninja-clang:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian12:$DEBIAN_12_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
    CMAKE_OPTIONS: -DENABLE_LDAP=NO
  extends: .linux-desktop

debian12-ninja-clang-sanitizer:
  variables:
    CMAKE_SANITIZER_OPTIONS: -DENABLE_SANITIZER=YES -DCMAKE_BUILD_TYPE=Debug
    ADDITIONAL_BUILD_OPTIONS: "-j 4"
  extends: debian12-ninja-clang

debian12-ninja-clang-novideo:
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_LDAP=NO
  extends: debian12-ninja-clang

debian12-ninja-clang-pqc:
  variables:
    CMAKE_OPTIONS: -DENABLE_PQCRYPTO=YES -DENABLE_LDAP=NO
  extends: debian12-ninja-clang

#################################################
# TESTS
#################################################



bctoolbox-debian12-test:
  extends: .test-bctoolbox
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

pqc-debian12-test:
  extends: .test-pqc
  <<: *docker_image_platform_and_runner_tag
  needs:
    - debian12-ninja-gcc-pqc

bellesip-debian12-test:
  extends: .test-bellesip
  needs:
    - debian12-ninja-gcc
  #different runner needed because belle-sip_tester can't work in parallel (dialog test suite is crashing randomly)
  tags: [ "docker-sequential" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian12:$DEBIAN_12_IMAGE_VERSION
  variables:
    PLATFORM: linux-debian12

belr-debian12-test:
  extends: .test-belr
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

belcard-debian12-test:
  extends: .test-belcard
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

bzrtp-debian12-test:
  extends: .test-bzrtp
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

liblinphone-debian12-test:
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian12-test-liblinphone:$DEBIAN_12_TEST_LIBLIN_IMAGE_VERSION
  extends: .test-liblinphone
  needs:
    - debian12-ninja-gcc
  variables:
    PLATFORM: linux-debian12

# liblinphone-debian12-test-mr:
#   extends: .test-liblinphone-mr
#   image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian12-test-liblinphone:$DEBIAN_12_TEST_LIBLIN_IMAGE_VERSION
#   needs:
#     - debian12-ninja-gcc
#   variables:
#     PLATFORM: linux-debian12
