wait-cache-synchro-rocky8:
  extends: .wait-cache-synchro
  variables:
    BUILD_SUBTYPE: rocky8
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SKIP_LINUX == null
    - !reference [ .wait-cache-synchro, rules ]

recache-rocky8:
  extends: .recache-update-cache
  image: !reference [ .rocky8_image_version, image ]

wait-cache-synchro-rocky8-python-wheel:
  extends: .wait-cache-synchro
  variables:
    BUILD_SUBTYPE: rocky8-python-wheel
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SKIP_LINUX == null
    - !reference [.rules-merge-request-manual, rules]

recache-rocky8-python-wheel:
  extends: .recache-update-cache
  allow_failure: true
  image: !reference [ .rocky8_python_wrapper_image_version, image ]

wait-cache-synchro-rocky8-ninja-gcc-tunnel-pq-h264-ekt:
  extends: .wait-cache-synchro
  variables:
    BUILD_SUBTYPE: rocky8-ninja-gcc-tunnel-pq-h264-ekt
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SKIP_LINUX == null
    - !reference [ .wait-cache-synchro, rules ]

recache-rocky8-ninja-gcc-tunnel-pq-h264-ekt:
  extends: .recache-update-cache
  image: !reference [ .rocky8_image_version, image ]
  variables:
    CACHE_JOB_NAME: rocky8-ninja-gcc-tunnel-pq-h264-ekt

wait-cache-synchro-rocky8-ninja-clang-mysql:
  extends: .wait-cache-synchro
  variables:
    BUILD_SUBTYPE: rocky8-ninja-clang-mysql
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SKIP_LINUX == null
    - !reference [ .wait-cache-synchro, rules ]

recache-rocky8-ninja-clang-mysql:
  extends: .recache-update-cache
  image: !reference [ .rocky8_image_version, image ]
  variables:
    CACHE_JOB_NAME: rocky8-ninja-clang-mysql

#Build template to use in other job scripts without having to copy same code
#format = .className: &referenceName
#Use = "<< *referenceName" to use the template ("-*" in script)


.factorize_rocky8: &docker_image_needs_platform_runner_tag_dev_toolset
  tags: [ "docker-test" ]
  image: !reference [ .rocky8_image_version, image ]
  needs:
    - rocky8-ninja-gcc
  variables:
    PLATFORM: linux-rocky8

#################################################
# Makefile
#################################################


rocky8-makefile-gcc:
  tags: [ "docker-flat" ]
  image: !reference [ .rocky8_image_version, image ]
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    #Only used to overwrite value set by .set_parallel_level.yml
    #ADDITIONAL_BUILD_OPTIONS: -j[jobs]
    CC: gcc
    CXX: g++
  extends: .linux-desktop
  needs:
    - wait-cache-synchro-rocky8


#################################################
# Ninja
#################################################


rocky8-ninja-gcc:
  stage: build
  tags: [ "docker-flat" ]
  image: !reference [ .rocky8_image_version, image ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
    CCACHE_SIZE: 15G
    CMAKE_OPTIONS: -DENABLE_EXAMPLE_PLUGIN=ON -DENABLE_CXX_WRAPPER=ON -DENABLE_LDAP=ON
    CMAKE_SANITIZER_OPTIONS: -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_SANITIZER=ON
  extends: .linux-desktop
  needs:
    - wait-cache-synchro-rocky8

rocky8-ninja-clang:
  tags: [ "docker-flat" ]
  image: !reference [ .rocky8_image_version, image ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
    CCACHE_SIZE: 15G
    CMAKE_OPTIONS: -DENABLE_EXAMPLE_PLUGIN=ON -DENABLE_CXX_WRAPPER=ON -DENABLE_LDAP=ON
    CMAKE_SANITIZER_OPTIONS: -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_SANITIZER=ON
  extends: .linux-desktop
  needs:
    - wait-cache-synchro-rocky8

rocky8-ninja-gcc-tunnel-pq-h264-ekt:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
  variables:
    CMAKE_OPTIONS: -DENABLE_LDAP=ON -DENABLE_NON_FREE_FEATURES=ON -DENABLE_OPENH264=ON -DENABLE_PQCRYPTO=ON -DENABLE_UNIT_TESTS=ON -DENABLE_TUNNEL=ON -DOPENSSL_ROOT_DIR=/usr/local -DENABLE_EKT_SERVER_PLUGIN=ON -DENABLE_CXX_WRAPPER=ON

 #Used to split cache name of frequently run jobs which run in parallel wich the same docker image
    CACHE_FALLBACK_KEY: "${CI_JOB_IMAGE}-master-6-non_protected"
  cache:
    - key: $CI_JOB_IMAGE-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG
      paths:
        - ccache/
  extends:
    - rocky8-ninja-gcc
  needs:
    - wait-cache-synchro-rocky8-ninja-gcc-tunnel-pq-h264-ekt

rocky8-ninja-clang-mysql:
  tags: [ "docker-flat" ]
  image: !reference [ .rocky8_image_version, image ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
    CCACHE_SIZE: 15G
    CMAKE_OPTIONS: -DWITH_SQLITE3=ON -DWITH_MYSQL=ON -DBUILD_SOCI_BACKENDS="mysql;sqlite3" -DCMAKE_BUILD_TYPE=RelWithDebInfo

 #Used to split cache name of frequently run jobs which run in parallel wich the same docker image
    CACHE_FALLBACK_KEY: "${CI_JOB_IMAGE}-master-6-non_protected"
  cache:
    - key: $CI_JOB_IMAGE-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG
      paths:
        - ccache/
  needs:
    - wait-cache-synchro-rocky8-ninja-clang-mysql
  extends:
    - .linux-desktop

rocky8-python-wheel:
  when: manual
  tags: [ "docker-flat" ]
  image: !reference [ .rocky8_python_wrapper_image_version, image ]
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
    ADDITIONAL_CMAKE_OPTIONS: -DWITH_SQLITE3=ON -DWITH_MYSQL=ON -DBUILD_SOCI_BACKENDS="mysql;sqlite3" -DPYTHON_EXECUTABLE:FILEPATH=/bin/python3.12 -DENABLE_VIDEO=OFF -DENABLE_SOUND=OFF

 #Used to split cache name of frequently run jobs which run in parallel wich the same docker image
    CACHE_FALLBACK_KEY: "${CI_JOB_IMAGE}-master-6-non_protected"
  cache:
    - key: $CI_JOB_IMAGE-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG
      paths:
        - ccache/

  extends: .linux-desktop-python
  needs:
    - wait-cache-synchro-rocky8-python-wheel
