wait-cache-synchro-debian12:
  extends: .wait-cache-synchro
  variables:
    BUILD_SUBTYPE: debian12
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SKIP_LINUX == null
    - !reference [.wait-cache-synchro, rules]

recache-debian12:
  extends: .recache-update-cache
  image: !reference [.debian12_image_version, image]

#Build template to use in other job scripts without having to copy same code
#format = .className: &referenceName
#Use = "<< *referenceName" to use the template ("-*" in script)


.factorize_debian12: &docker_image_platform_and_runner_tag
  tags: [ "docker-test" ]
  image: !reference [.debian12_image_version, image]
  variables:
    PLATFORM: linux-debian12

#################################################
# Makefile
#################################################


debian12-makefile-gcc:

  tags: [ "docker" ]
  image: !reference [.debian12_image_version, image]
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .linux-desktop


debian12-makefile-clang:

  tags: [ "docker" ]
  image: !reference [.debian12_image_version, image]
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .linux-desktop


#################################################
# Ninja
#################################################


debian12-ninja-gcc:

  tags: [ "docker" ]
  image: !reference [.debian12_image_version, image]
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
    CMAKE_OPTIONS: -DENABLE_LDAP=OFF
  extends: .linux-desktop
  needs:
    - wait-cache-synchro-debian12

debian12-ninja-gcc-novideo:
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=OFF -DENABLE_LDAP=OFF
  extends: debian12-ninja-gcc

debian12-ninja-gcc-pqc:
  variables:
    CMAKE_OPTIONS: -DENABLE_NON_FREE_FEATURES=ON -DENABLE_PQCRYPTO=ON -DENABLE_LDAP=OFF
  extends: debian12-ninja-gcc

debian12-ninja-gcc-smallsdk:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=OFF -DENABLE_ADVANCED_IM=OFF -DENABLE_DB_STORAGE=OFF -DENABLE_FLEXIAPI=OFF -DENABLE_LDAP=OFF
  extends: debian12-ninja-gcc

debian12-ninja-gcc-openssl:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
  variables:
    CMAKE_OPTIONS: -DENABLE_OPENSSL=ON -DENABLE_MBEDTLS=OFF -DENABLE_LDAP=ON
  extends: debian12-ninja-gcc

debian12-ninja-clang:
  tags: [ "docker" ]
  image: !reference [.debian12_image_version, image]
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
    CMAKE_OPTIONS: -DENABLE_LDAP=OFF
  extends: .linux-desktop

debian12-ninja-clang-sanitizer:
  variables:
    CMAKE_SANITIZER_OPTIONS: -DENABLE_SANITIZER=ON -DCMAKE_BUILD_TYPE=Debug
    ADDITIONAL_BUILD_OPTIONS: "-j 4"
  extends: debian12-ninja-clang

debian12-ninja-clang-novideo:
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=OFF -DENABLE_LDAP=OFF
  extends: debian12-ninja-clang

debian12-ninja-clang-pqc:
  variables:
    CMAKE_OPTIONS: -DENABLE_NON_FREE_FEATURES=ON -DENABLE_PQCRYPTO=ON -DENABLE_LDAP=OFF
  extends: debian12-ninja-clang

debian12-ninja-gcc-python-wheel:
  tags: [ "docker" ]
  image: !reference [.debian12_image_version, image]
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  extends: .linux-desktop-python

#################################################
# TESTS
#################################################



bctoolbox-debian12-test:
  extends: .test-bctoolbox
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

bctoolbox-debian12-openssl-test-mr:
  extends: .test-bctoolbox-mr
  needs:
    - debian12-ninja-gcc-openssl
  <<: *docker_image_platform_and_runner_tag


pqc-debian12-test:
  extends: .test-pqc
  <<: *docker_image_platform_and_runner_tag
  needs:
    - debian12-ninja-gcc-pqc

bellesip-debian12-test:
  extends: .test-bellesip
  needs:
    - debian12-ninja-gcc
  #different runner needed because belle-sip_tester can't work in parallel (dialog test suite is crashing randomly)
  tags: [ "docker-sequential" ]
  image: !reference [.debian12_image_version, image]
  variables:
    PLATFORM: linux-debian12

belr-debian12-test:
  extends: .test-belr
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

belcard-debian12-test:
  extends: .test-belcard
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

bzrtp-debian12-test:
  extends: .test-bzrtp
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

ortp-debian12-test:
  extends: .test-ortp
  needs:
    - debian12-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

liblinphone-debian12-test:
  image: !reference [.debian12_test_libl_image_version, image]
  extends: .test-liblinphone
  needs:
    - debian12-ninja-gcc
  variables:
    PLATFORM: linux-debian12

liblinphone-debian12-openssl-test-mr:
   image: !reference [.debian12_test_libl_image_version, image]
   extends: .test-liblinphone-crypto-backend-mr
   needs:
     - debian12-ninja-gcc-openssl
   variables:
     PLATFORM: linux-debian12
