# Copyright (c) 2010-2025 Belledonne Communications SARL.
#
# This file is part of mediastreamer2
# (see https://gitlab.linphone.org/BC/public/mediastreamer2).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

"""Run and analyze the tests of the linphone-sdk suite Noise Suppression in mediastreamer2.

The tests are run, then the results are analyed to measure the quality of the denoising.
The metrics are read from the log file and plot with the audio signals.
An additional metric based on MFCC representation is computed.
"""

import os
from pathlib import Path
from typing import Any

from tools.common.utils.sdk_test import SDKTest
from tools.noise_suppression.audio_analysis_noise_suppression import (
    AudioAnalysisNoiseSuppression,
)
from tools.noise_suppression.noise_suppression_files import NoiseSuppressionFiles


class NoiseSuppressionTest(SDKTest):
    """Run and analyze a test of the linphone-sdk suite Noise Suppression in mediastreamer2."""

    def __init__(self, test_name: str, build_path: Path, **kwargs: dict[str, Any]) -> None:
        """Define the test.

        The test is defined by test_name, and the paths needed to run it can be given in kwargs.
        :param test_name: Name of the test or the related function in file mediastreamer2_noise_suppression_tester.c.
        :type test_name: str
        :param build_path: Path to build directory. It contains the executable at bin/mediastreamer2-tester.
        :type build_path: Path
        :param kwargs: Optional arguments to configure the test. Possible keys are:
            - "output path" (Path, optional): Path to the output directory, where the log file is written. If not
            provided, it is the build directory.
            - "start analysis" (int, optional): Time stamp taken to start the audio analysis, in ms. If not provided,
            the analysis starts at 0 ms.
        :param kwargs: dict[str, Any]
        :raises ValueError: if the mediastreamer2-tester executable is not found in build path.
        """
        SDKTest.__init__(
            self,
            "mediastreamer2-tester",
            "Noise suppression",
            test_name,
            build_path,
            kwargs.get("output path", build_path),
        )
        self.files = NoiseSuppressionFiles()
        self.files.noisy_speech.file_name = self.output_path + "noisy_audio_" + self.test_name + ".wav"
        self.files.clean.file_name = self.output_path + "clean_audio_" + self.test_name + ".wav"
        self.start_analysis_ms = kwargs.get("start analysis", 0)
        self.alignment_interval_ms = kwargs.get("alignment interval")

    def move_files(self) -> None:
        """Move the file generated by the test to another folder.

        Make sure that the output file is not deleted at the end of the test.
        The output file is the latest wav file starting with clean_.
        """
        audio_file_list = list(Path.cwd().glob("clean_*" + self.test_name + "*.wav"))
        audio_file_list.sort(key=os.path.getmtime)
        if len(audio_file_list) > 0:
            audio_file_name = audio_file_list[-1]
            print(f"move {audio_file_name}")
            file_name = self.files.clean.file_name
            print(f"into {file_name}")
            src = Path(audio_file_name)
            dst = Path(file_name)
            src.rename(dst)
        else:
            print(
                "no audio file name matching",
                "clean*_" + self.test_name + "*.wav",
                "in build dir to move",
            )

    def get_results(self, plot_fig: bool = False) -> dict[str, str | float]:
        """Get the audio denoising quality metrics.

        Extract the denoising metrics from the logs, compute the MFCC metric, display the results and the audio.
        All the results are returned in a dictionary.
        :param plot_fig: optional, True to display the audio with silence and talk parts, False otherwise. Default is
            False.
        :type plot_fig: bool
        :return: dictionary of test results and metrics.
        :rtype: dict[str, str | float]
        """
        print(f"\nAnalyze results in file\n\t{self.log_file}")
        try:
            if self.files.clean.data is None:
                print(f"read clean audio from file {self.files.noisy_speech.file_name}")
                self.files.clean.read_audio()
            if self.files.speech.data is None:
                print(f"read speech audio from file {self.files.noisy_speech.file_name}")
                self.files.speech.read_audio()
            if self.files.noisy_speech.data is None:
                print(f"read noisy speech audio from file {self.files.noisy_speech.file_name}")
                self.files.noisy_speech.read_audio()
            self.results = AudioAnalysisNoiseSuppression(
                self.files.speech,
                self.files.noisy_speech,
                self.files.clean,
                self.test_suite_name,
            )
            self.results.compute_denoising_quality(
                self.log_file,
                self.start_analysis_ms,
                self.alignment_interval_ms,
                plot_fig,
            )
        except FileNotFoundError:
            print("no audio file to analyse")
            self.results = AudioAnalysisNoiseSuppression(None, None, None)
            self.results.get_results(self.log_file)

        print("--- results ---")
        self.results.print()
        return {
            "test": self.test_name,
            "similarity": self.results.similarity_in_speech,
            "similarity with MFCC": self.results.similarity_mfcc,
            "energy in silence": self.results.energy_in_silence,
            "energy in silence with noise": self.results.energy_in_silence_with_noise,
            "asserts": self.results.asserts,
            "test passed": self.results.test_passed,
            "time": self.results.total_time_s,
            "max pos": self.results.maxpos,
            "MSTicker late": self.results.msticker_late_ms,
            "filter count": self.results.filter_stats[0],
            "filter min time": self.results.filter_stats[1],
            "filter mean time": self.results.filter_stats[2],
            "filter max time": self.results.filter_stats[3],
            "filter std time": self.results.filter_stats[4],
            "filter CPU usage": self.results.filter_stats[5],
        }
