.TH ASSERT 3 "September 2001" "" "CUnit Programmer's Manual"

.SH "NAME"
ASSERT \- Register failure and return from the function if assertion false. 

.SH "SYNOPSIS"
.B #include <CUnit/CUnit.h>
.TP
.B ASSERT(int expression)
.TP
.B ASSERT_TRUE(value)
.TP
.B ASSERT_FALSE(value)
.TP
.B ASSERT_EQUAL(actual, expected)
.TP
.B ASSERT_NOT_EQUAL(actual, expected)
.TP
.B ASSERT_PTR_EQUAL(actual, expected)
.TP
.B ASSERT_PTR_NOT_EQUAL(actual, expected)
.TP
.B ASSERT_PTR_NULL(value)
.TP
.B ASSERT_PTR_NOT_NULL(value)
.TP
.B ASSERT_STRING_EQUAL(actual, expected)
.TP
.B ASSERT_STRING_NOT_EQUAL(actual, expected)
.TP
.B ASSERT_NSTRING_EQUAL(actual, expected, count)
.TP
.B ASSERT_NSTRING_NOT_EQUAL(actual, expected, count)
.TP
.B ASSERT_DOUBLE_EQUAL(actual, expected, granularity)
.TP
.B ASSERT_DOUBLE_NOT_EQUAL(actual, expected, granularity)

.SH "DESCRIPTION"
.B "ASSERT"
registers the failure condition if expression evluates to 
false and returns from the calling function else it doesn't do anything 
and the normal excution flow is continued. Similarly other asserts are self-descriptive.
A brief description for each of the groups is as follows,
.TP 1
.B ASSERT_TRUE - Asserts if the value is not TRUE
.TP 1
.B ASSERT_FALSE - Asserts if the value is not FALSE
.TP 1
.B ASSERT_EQUAL - Asserts if the two given values are not equal
.TP 1
.B ASSERT_NOT_EQUAL - Asserts if the two given values are equal
.TP 1
.B ASSERT_PTR_EQUAL - Asserts if the two given pointers are not same
.TP 1
.B ASSERT_PTR_NOT_EQUAL - Asserts if the two given pointers are same
.TP 1
.B ASSERT_PTR_NULL - Asserts if the given pointer is NULL
.TP 1
.B ASSERT_PTR_NOT_NULL - Asserts if the given pointer is not NULL
.TP 1
.B ASSERT_STRING_EQUAL - Asserts if the two given string values are not same
.TP 1
.B ASSERT_STRING_NOT_EQUAL - Asserts if the two given string values are same
.TP 1
.B ASSERT_NSTRING_EQUAL - Asserts if the two given string values are not equal for 'n' chars
.TP 1
.B ASSERT_NSTRING_NOT_EQUAL - Asserts if the two given values are equal for 'n' chars
.TP 1
.B ASSERT_DOUBLE_EQUAL - Asserts if the two given values are not equal for granularity specified 
        i.e |actual - expected| > |granularity|
.TP 1
.B ASSERT_DOUBLE_NOT_EQUAL - Asserts if the two given values are equal for granularity specified 
        i.e |actual - expected| <= |granularity|

.SH "RETURN VALUE"
No value is returned.

.SH "AUTHOR"
Anil Kumar <aksaharan@yahoo.com>

.SH "WEBSITE"
http://cunit.sourceforge.net
