.TH "Console Test" 3 "September 2001" "" "CUnit Programmer's Manual"

.SH "NAME"
console_run_tests - Start CUnit tests in console mode

.SH "SYNOPSIS"
.B #include <CUnit/Console.h>
.TP
.BR "void console_run_tests(void);"

.SH "DESCRIPTION"
.B "console_run_tests"
interface to run test cases in console based interface.

.SH "RETURN VALUE"
It does not returns any value.

.SH "SEE ALSO"
.BR "ASSERT" (3),
.BR "add_test_case" (3),
.BR "add_test_group" (3),
.BR "automated_run_tests" (3),
.BR "curses_run_tests" (3),
.BR "cleanup_registry" (3),
.BR "CUnit" (8),
.BR "initialize_registry" (3), 
.BR "get_registry" (3),
.BR "set_registry" (3),
.BR "get_error" (3).

.SH "AUTHOR"
Anil Kumar <aksaharan@yahoo.com>

.SH "WEBSITE"
http://cunit.sourceforge.net
