.TH get_error 3 "September 2001" "" "CUnit Programmer's Manual"

.SH "NAME"
get_error - gets the error description.

.SH "SYNOPSIS"
.B #include <CUnit/TestDB.h>
.TP
.BR "const char* get_error(void);"

.SH "DESCRIPTION"
.B "get_error"
gets the error description for the immediately occurred error 
corresponding to the error number that is set in the CUnit library. 
It returns description only for valid error occurrences/codes.

.SH "RETURN VALUE"
On successfuly operation
.B "get_error"
returns a
.B "const char*"
which contains the error description.
		
.SH "SEE ALSO"
.BR "CUnit" (8),

.SH "AUTHOR"
Anil Kumar <aksaharan@yahoo.com>

.SH "WEBSITE"
http://cunit.sourceforge.net
