.TH "Test Registry" 3 "September 2001" "" "CUnit Programmer's Manual"

.SH "NAME"
initialize_registry, cleanup_registry - Initialize/Cleanup test registry

.SH "SYNOPSIS"
.B #include <CUnit/TestDB.h>
.TP
.BR "int initialize_registry(void);"
.TP
.BR "void cleanup_registry(void);"

.SH "DESCRIPTION"
.B "initialize_registry"
initializes the state of the test registry.
.B "cleanup_registry"
cleans/frees up the resources used by the test registry.

.SH "RETURN VALUE"
.B "cleanup_registry"
does not returns any status.
.B "initialize_registry"
returns following status codes,
.TP 2
.B "CUE_SUCESS"
Registry initialized successfully
.TP 2
.B "CUE_NOMEMORY"
Memory allocation failed for internal use
		
.SH "SEE ALSO"
.BR "CUnit" (8),
.BR "add_test_case" (3),
.BR "add_test_group" (3)

.SH "AUTHOR"
Anil Kumar <aksaharan@yahoo.com>

.SH "WEBSITE"
http://cunit.sourceforge.net
