.TH "Automated Test" 3 "September 2001" "" "CUnit Programmer's Manual"

.SH "NAME"
set_output_filename - Set output filename prefix

.SH "SYNOPSIS"
.B #include <CUnit/Automated.h>
.TP
.BR "void set_output_filename(void);"

.SH "DESCRIPTION"
.B "set_output_filename"
It sets the output file name prefix to be used by the Automated test run.

.SH "RETURN VALUE"
It does not returns any value.

.SH "SEE ALSO"
.BR "ASSERT" (3),
.BR "add_test_case" (3),
.BR "add_test_group" (3),
.BR "automated_run_tests" (3),
.BR "curses_run_tests" (3),
.BR "cleanup_registry" (3),
.BR "CUnit" (8),
.BR "initialize_registry" (3), 
.BR "get_registry" (3),
.BR "set_registry" (3),
.BR "get_error" (3).

.SH "AUTHOR"
Anil Kumar <aksaharan@yahoo.com>

.SH "WEBSITE"
http://cunit.sourceforge.net
