nuget-upload-xamarin:
  stage: deploy
  tags: [ "macmini-m1-xcode12" ]

  rules:
    - if: $DEPLOY_RUN_NUGET
    - if: $UPLOAD_XAMARIN
    - if: $NIGHTLY_MASTER && $SKIP_DEPLOY == null
    - if: $NIGHTLY_RELEASE

  variables:
    GIT_STRATEGY: none # We don't need sources for this job.

  needs:
    - job: xamarin-package
  
  before_script:
    - nuget sources Add -Name gitlab -Source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" -UserName gitlab-ci-token -Password $CI_JOB_TOKEN -StorePasswordInClearText

  script:
    - "echo 'You can find uploaded nuget packages here: https://gitlab.linphone.org/BC/public/linphone-sdk/-/packages'"
    - nuget push "results/packages/*.nupkg" -Source gitlab

  after_script:
    - nuget sources Remove -Name gitlab
