xamarin-upload:
  stage: deploy
  tags: [ "deploy" ]

  rules:
    - if: $UPLOAD_XAMARIN
    - if: $NIGHTLY_RELEASE

  needs:
    - xamarin-package

  script:
    - UPLOAD_ROOT_DIRECTORY=$DEPLOY_RELEASES_DIRECTORY
    - echo $UPLOAD_ROOT_DIRECTORY

    - LIBLINPHONE_DESCRIBE=$(git -C liblinphone describe)
    - echo $LIBLINPHONE_DESCRIBE
    - echo $LIBLINPHONE_DESCRIBE | grep -Eq ".*(alpha|beta).*" || IS_ALPHA_BETA=$?

    - |
        if [ $IS_ALPHA_BETA -eq 0 ];
        then UPLOAD_ROOT_DIRECTORY=$DEPLOY_SNAPSHOTS_ROOT_DIRECTORY
        fi
    - echo $UPLOAD_ROOT_DIRECTORY
    - rsync -rlv results/xamarin/* $DEPLOY_SERVER:$UPLOAD_ROOT_DIRECTORY/xamarin
