xamarin-upload:
  stage: deploy
  tags: [ "deploy" ]

  rules:
    - if: $DEPLOY_RUN_NUGET
    - if: $UPLOAD_XAMARIN
    - if: $NIGHTLY_MASTER

  needs:
    - xamarin-package

  script:
    - DESCRIBE=$(git -C liblinphone describe)
    - !reference [.choose_upload_dir, script]
    - rsync -rlv --dry-run results/packages/* $DEPLOY_SERVER:$UPLOAD_ROOT_DIRECTORY/xamarin
