xamarin-upload:
  stage: deploy
  tags: [ "deploy" ]

  variables:
    GIT_FETCH_EXTRA_FLAGS: --tags --force --recurse-submodules=yes
    GIT_SUBMODULE_UPDATE_FLAGS: --jobs 8 --force --recursive

  rules:
    - if: $UPLOAD_XAMARIN
    - if: $NIGHTLY_RELEASE

  needs:
    - xamarin-package

  script:

    - DESCRIBE=$(git -C liblinphone describe)
    - echo $DESCRIBE

    - LIBLINPHONE_VERSION=$(echo $DESCRIBE| grep -o -E '^[0-9]+\.[0-9]+')

    - echo $LIBLINPHONE_VERSION

    - !reference [.choose_upload_dir, script]

    - rsync -rlv results/xamarin/* $DEPLOY_SERVER:$UPLOAD_ROOT_DIRECTORY/xamarin
