.android-upload-common:
  stage: deploy
  tags: [ "docker" ]
  image: !reference [.android_r27_image_version, image]

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_RUN_ANDROID != null
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_ANDROID != null && $SKIP_DEPLOY == null

  variables:
    CCACHE_SIZE: 4G
    GIT_STRATEGY: fetch
    GRADLE_OPTIONS: -i
    MAVEN_REPO_PATH: linphone-sdk-android*

  before_script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_USER_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$DEPLOY_SERVER_HOST_KEY" >> ~/.ssh/known_hosts

  script:
    - git config --global user.email "gitlab@belledonne-communications.com"
    - git config --global user.name "Gitlab"
    - cd build/android
    - mkdir -p maven_repository/org/linphone/
    - echo $MAVEN_REPO_PATH
    - rsync -avzP -e ssh --exclude "*.aar" --exclude "*.jar" $MAVEN_REPO_URL/org/linphone/$MAVEN_REPO_PATH maven_repository/org/linphone/
    - echo $GRADLE_OPTIONS
    - ../../cmake/Android/gradlew -b upload.gradle publish $GRADLE_OPTIONS
    - rsync -avzP -e ssh ./maven_repository/org/linphone/$MAVEN_REPO_PATH $MAVEN_REPO_URL/org/linphone/

  after_script:
    - rm -rf ~/.ssh || true

android-doc-upload:
  stage: deploy
  tags: [ "docker" ]
  image: !reference [.android_r27_image_version, image]

  rules:
    - if: $DEPLOY_RUN_ANDROID != null
    - if: $DEPLOY_ANDROID != null && $SKIP_DEPLOY == null

  variables:
    CCACHE_SIZE: 4G
    GIT_STRATEGY: fetch
    GIT_FETCH_EXTRA_FLAGS: --tags --force --recurse-submodules=yes
    GIT_SUBMODULE_UPDATE_FLAGS: --jobs 8 --force --recursive

  needs:
    - android-ninja-r27

  before_script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_USER_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$DEPLOY_SERVER_HOST_KEY" >> ~/.ssh/known_hosts

  script:
    - git config --global user.email "gitlab@belledonne-communications.com"
    - git config --global user.name "Gitlab"

    #debug empty value on updated arch
    - find $CI_PROJECT_DIR -name '.git' -exec bash -c 'git config --global --add safe.directory ${0%/.git}' {} \;
    - git describe --debug || true
    - git -C liblinphone describe --debug || true

    #Only get major and minor version (ex: 4.4) for documentation directory

    #git -C executes the git command in specified directory
    #grep options:
    #-o means print only matched pattern instead of whole line
    #-E means extended regexp, see https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions
    - DESCRIBE=$(git -C liblinphone describe)
    - echo $DESCRIBE


    - LIBLINPHONE_VERSION=$(echo $DESCRIBE | grep -o -E '^[0-9]+\.[0-9]+')

    - !reference [.choose_upload_dir, script]

    - cd build/android
    - ssh $DEPLOY_SERVER mkdir -p $UPLOAD_ROOT_DIRECTORY/docs/liblinphone/$LIBLINPHONE_VERSION/java
    - rsync -rlv -e ssh linphone-sdk/bin/docs/javadoc/* $DEPLOY_SERVER:$UPLOAD_ROOT_DIRECTORY/docs/liblinphone/$LIBLINPHONE_VERSION/java/

  after_script:
    - rm -rf ~/.ssh || true

android-upload:
  extends: .android-upload-common
  variables:
    MAVEN_REPO_URL: $ANDROID_MAVEN_URL
  needs:
    - android-ninja-r27

android-upload-no-video:
  extends: .android-upload-common
  variables:
    MAVEN_REPO_URL: $ANDROID_MAVEN_URL
    GRADLE_OPTIONS: -Pno-video -i
    MAVEN_REPO_PATH: no-video
  needs:
    - android-ninja-r27-no-video

android-upload-minimal-size:
  extends: .android-upload-common
  variables:
    MAVEN_REPO_URL: $ANDROID_MAVEN_URL
    GRADLE_OPTIONS: -Pminimal-size -i
    MAVEN_REPO_PATH: minimal
  needs:
    - android-ninja-r27-minimal-size

android-upload-g729-ldap-post-quantum:
  extends: .android-upload-common
  variables:
    MAVEN_REPO_URL: $ANDROID_PRIVATE_MAVEN_URL
  needs:
    - android-makefile-r27-g729-ldap-post-quantum
