cmake_policy(SET CMP0009 NEW)

set(CHANGES "")
foreach(SOURCE_DIR ${SOURCE_DIRS})
	file(GLOB_RECURSE SOURCE_FILES LIST_DIRECTORIES false RELATIVE "${SOURCE_DIR}" "${SOURCE_DIR}/*")
	foreach(SOURCE_FILE ${SOURCE_FILES})
		file(TIMESTAMP "${SOURCE_DIR}/${SOURCE_FILE}" SOURCE_FILE_TIMESTAMP UTC)
		set(CHANGES "${CHANGES}${SOURCE_FILE}\t${SOURCE_FILE_TIMESTAMP}\n")
	endforeach()
endforeach()

if(EXISTS "${BINARY_DIR}/check_changes.txt")
	file(READ "${BINARY_DIR}/check_changes.txt" OLD_CHANGES)
	if(NOT CHANGES STREQUAL OLD_CHANGES)
		file(WRITE "${BINARY_DIR}/check_changes.txt" "${CHANGES}")
	endif()
else()
	file(WRITE "${BINARY_DIR}/check_changes.txt" "${CHANGES}")
endif()
