.vs-nuget-windows-package:
  stage: package
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DEPLOY_RUN_WINDOWS != null
    - if: $CI_PIPELINE_SOURCE == "schedule" && $WINDOWS_PACKAGE != null
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .gitlab-ci-files/windows/packages.yml
        - cmake/NuGet/Windows/**/*
    - if: $DEPLOY_RUN_NUGET != null
  script:
    - cd build

    # We are forced to do it in brackets because powershell displays an human readable object with useless line returns by default...
    - (Get-Location).path > chdir_sdk.temp
    - Set-Variable -Name "OUTPUT_SDK_BUILD" -Value ($(Get-Content chdir_sdk.temp))
    - Write-Output $OUTPUT_SDK_BUILD
    - Write-Output $DEFAULT_CMAKE_OPTIONS
    - Write-Output $CMAKE_OPTIONS
    - Write-Output $CMAKE_ARCHITECTURE
    - Write-Output $SCHEDULE_CMAKE_OPTIONS

    - echo $LastExitCode

    # We use Invoke-Expression to explain to powershell that we don't want it to touch to spaces in arguments
    - Invoke-Expression "& cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLINPHONESDK_BUILD_TYPE=Packager -DLINPHONESDK_PACKAGER=Nuget -DLINPHONESDK_DESKTOP_ZIP_PATH=$OUTPUT_SDK_BUILD/win -DLINPHONESDK_UWP_ZIP_PATH=$OUTPUT_SDK_BUILD/uwp -DLINPHONESDK_WINDOWSSTORE_ZIP_PATH=$OUTPUT_SDK_BUILD/winstore -DLINPHONESDK_WINDOWS_ARCHS=x86 -DLINPHONESDK_WINDOWSSTORE_ARCHS=x86 $DEFAULT_CMAKE_OPTIONS $CMAKE_OPTIONS $CMAKE_ARCHITECTURE $SCHEDULE_CMAKE_OPTIONS"

    - echo $LastExitCode
    - 'if (-not ($LastExitCode -eq 0)) {throw "Error: Configure failed"}'

    - cmake --build . --target ALL_BUILD --config RelWithDebInfo -- /maxcpucount /nodeReuse:true /p:TrackFileAccess=false

    - echo $LastExitCode
    - 'if (-not ($LastExitCode -eq 0)) {throw "Error: Build failed"}'
  artifacts:
    paths:
      - build/linphone-sdk/packages/*
    when: always
    expire_in: 1 week

vs2022-nuget-windows-package:
  extends: .vs-nuget-windows-package
  tags: [ "windows-powershell-vs-17-2022" ]
  needs:
  - vs2022-win32store-scheduled-windows
  - vs2022-uwp-windows
  - vs2022-win32-scheduled-windows

vs2019-nuget-windows-package:
  extends: .vs-nuget-windows-package
  tags: [ "windows-powershell-vs-16-2019" ]
  rules:
    - !reference [.rules-merge-request-manual, rules]
  needs:
  - vs2019-win32store-scheduled-windows
  - vs2019-uwp-scheduled-windows
  - vs2019-win32-scheduled-windows

vs2017-nuget-windows-package:
  extends: .vs-nuget-windows-package
  tags: [ "windows-powershell-vs-15-2017" ]
  rules:
    - !reference [.rules-merge-request-manual, rules]
  needs:
  - vs2017-win32store-scheduled-windows
  - vs2017-uwp-scheduled-windows
  - vs2017-win32-scheduled-windows
